# -*- coding: utf-8 -*-
"""Helipe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgE_S2OFa3xLQ1mf60nAKyByLm4AXVD-
"""

pip install gspread google-auth

import streamlit as st
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime, timedelta

# --- CONFIGURAÇÕES DO GOOGLE SHEETS ---
ID_PLANILHA = "1vOjr5SnrTHHf6lV5pP73nyfl42QwWiahw25lvHFCKnw"

def connect_sheets():
    scope = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
    creds = Credentials.from_service_account_file("credenciais.json", scopes=scope)
    client = gspread.authorize(creds)
    return client.open_by_key(ID_PLANILHA)

# Tenta conectar e carregar os dados
try:
    sh = connect_sheets()
except Exception as e:
    st.error(f"Erro de conexão: {e}")

# --- ESTILIZAÇÃO HELIPE ---
st.markdown("""
    <style>
    .stApp { background-color: #FDFBF7; }
    [data-testid="stSidebar"] { background-color: #A3AD8B !important; }
    .stButton>button { background-color: #8B5A2B; color: white; border-radius: 6px; border: none; width: 100%; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 2px 2px 5px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES DE LÓGICA (BACKEND) ---

def mover_para_fluxo(aba_origem, id_linha, descricao, valor, tipo):
    """Move um item pago/recebido para a aba Fluxo_Caixa"""
    try:
        ws_origem = sh.worksheet(aba_origem)
        ws_fluxo = sh.worksheet("Fluxo_Caixa")

        # Registra no fluxo
        data_hoje = datetime.now().strftime("%d/%m/%Y")
        ws_fluxo.append_row([data_hoje, tipo, descricao, valor, aba_origem])

        # Aqui no sistema real, marcaríamos o Check na planilha
        st.success(f"Lançamento realizado no Fluxo de Caixa!")
    except:
        st.error("Erro ao processar transação financeira.")

def explosao_estoque(nome_kit, qtd_produzir):
    """Calcula quanto de MP será necessário para a produção desejada"""
    # Carrega as tabelas
    mp_df = pd.DataFrame(sh.worksheet("Estoque_MP").get_all_records())
    pecas_df = pd.DataFrame(sh.worksheet("Estoque_Pecas").get_all_records())

    # Exemplo de lógica simplificada para demonstração na tela
    st.write(f"### Planejamento de Produção: {qtd_produzir}x {nome_kit}")
    # (A lógica completa de recursão Kit->Montagem->Peça entraria aqui)
    st.info("Calculando necessidade de Pinus, Cola e Ferragens...")

# --- INTERFACE (FRONTEND) ---

if 'page' not in st.session_state: st.session_state.page = 'Dashboard'
def navegar(p): st.session_state.page = p

with st.sidebar:
    try: st.image("logo.png", width=150)
    except: st.title("HELIPE ATELIÊ")

    st.write("---")
    if st.button("📊 Dashboard"): navegar('Dashboard')
    if st.button("💰 Financeiro"): navegar('Financeiro')
    if st.button("📦 Estoque & Produção"): navegar('Estoque')
    if st.button("📋 Pedidos"): navegar('Pedidos')
    if st.button("🚚 Expedição"): navegar('Expedicao')
    st.write("---")
    if st.button("⬅ Voltar"): navegar('Dashboard')

# --- TELAS ---

if st.session_state.page == 'Dashboard':
    st.title("🌿 Painel de Controle Helipe")
    col1, col2, col3 = st.columns(3)
    col1.metric("Contas a Pagar", "R$ 450,00")
    col2.metric("Pedidos Pendentes", "8")
    col3.metric("Estoque Crítico", "Pinus 20mm")

    st.write("### Produção em Andamento")
    # Aqui leria a aba 'Producao_OP'
    st.dataframe(pd.DataFrame(sh.worksheet("Producao_OP").get_all_records()))

elif st.session_state.page == 'Financeiro':
    st.title("💰 Gestão Financeira")
    tab1, tab2, tab3 = st.tabs(["Contas a Pagar", "Contas a Receber", "Fluxo de Caixa"])

    with tab1:
        df_pagar = pd.DataFrame(sh.worksheet("Financeiro_Pagar").get_all_records())
        st.dataframe(df_pagar)
        if st.button("Confirmar Pagamento Selecionado"):
            # Lógica para pegar a linha selecionada e mover
            st.info("Funcionalidade: O sistema moverá este item para o Fluxo de Caixa.")

    with tab3:
        df_fluxo = pd.DataFrame(sh.worksheet("Fluxo_Caixa").get_all_records())
        st.write("#### Histórico de Entradas e Saídas")
        st.table(df_fluxo)

elif st.session_state.page == 'Estoque':
    st.title("📦 Marcenaria - Estoque e Explosão")
    cat = st.selectbox("Categoria", ["MP - Matéria Prima", "Peças", "Montagens", "Kits"])

    if cat == "MP - Matéria Prima":
        df_mp = pd.DataFrame(sh.worksheet("Estoque_MP").get_all_records())
        st.dataframe(df_mp)

    st.write("---")
    st.write("### 🔨 Calculadora de Explosão de Materiais")
    col_k, col_q = st.columns(2)
    kit = col_k.selectbox("Selecione o Kit para Produção", ["Torre de Aprendizagem", "Cubo Sensorial", "Prateleira Lúdica"])
    qtd = col_q.number_input("Quantidade de Kits", min_value=1, value=1)

    if st.button("Calcular Necessidade de Compra"):
        explosao_estoque(kit, qtd)

elif st.session_state.page == 'Pedidos':
    st.title("📋 Pedidos")
    df_pedidos = pd.DataFrame(sh.worksheet("Pedidos").get_all_records())

    for i, row in df_pedidos.iterrows():
        # Lógica de Cores baseada no prazo
        prazo = row['Prazo_Producao']
        cor = "#E8F5E9" # Verde padrão
        if prazo == "Em estoque": cor = "#FFEBEE" # Vermelho

        st.markdown(f"""
            <div style="background-color:{cor}; padding:15px; border-radius:10px; border:1px solid #ddd; margin-bottom:10px; color:black;">
                <strong>Pedido: {row['N_Pedido']} - Cliente: {row['Cliente']}</strong><br>
                Status: {prazo} | Valor: R$ {row['Valor_Total']}
            </div>
        """, unsafe_allow_html=True)

elif st.session_state.page == 'Expedicao':
    st.title("🚚 Expedição e Logística")
    df_exp = pd.DataFrame(sh.worksheet("Expedicao").get_all_records())
    st.write("Marque as etapas concluídas:")
    for i, row in df_exp.iterrows():
        c1, c2, c3, c4 = st.columns([1,1,1,1])
        c1.write(f"Ped: {row['ID_Pedido']}")
        if c2.checkbox("Etiqueta", key=f"et_{i}"): pass
        if c3.checkbox("Embalado", key=f"em_{i}"): pass
        if c4.checkbox("Enviado", key=f"en_{i}"): pass